const BSV_MARKET_PROTOCOL_VERSION = '1.0.0';
const BSV_MARKET_RELEASE_BOOTSTRAP_HEIGHT = 947111;
const BSV_MARKET_RELEASE_BOOTSTRAP_PREV_HEIGHT = BSV_MARKET_RELEASE_BOOTSTRAP_HEIGHT - 1;
const BSV_MARKET_RELEASE_BOOTSTRAP_PREV_HASH = '00000000000000001395f00ef625272e81c0f3191c5164bc67a17d91e0161d9f';
const BSV_MARKET_RELEASE_ID = `bsv-market-protocol-v${BSV_MARKET_PROTOCOL_VERSION}-h${BSV_MARKET_RELEASE_BOOTSTRAP_HEIGHT}`;

function buildProtocolReleaseInfo() {
  return {
    protocolVersion: BSV_MARKET_PROTOCOL_VERSION,
    releaseId: BSV_MARKET_RELEASE_ID,
    bootstrapHeight: BSV_MARKET_RELEASE_BOOTSTRAP_HEIGHT,
    bootstrapPrevHeight: BSV_MARKET_RELEASE_BOOTSTRAP_PREV_HEIGHT,
    bootstrapPrevHash: BSV_MARKET_RELEASE_BOOTSTRAP_PREV_HASH,
  };
}

module.exports = {
  BSV_MARKET_PROTOCOL_VERSION,
  BSV_MARKET_RELEASE_ID,
  BSV_MARKET_RELEASE_BOOTSTRAP_HEIGHT,
  BSV_MARKET_RELEASE_BOOTSTRAP_PREV_HEIGHT,
  BSV_MARKET_RELEASE_BOOTSTRAP_PREV_HASH,
  buildProtocolReleaseInfo,
};
